#!/bin/bash -eux

sudo -v

if [ "$1" eq "open" ]; then
    command=allow
else
    command=delete
fi

echo "> ufw $command proto tcp from any to any port 443"
ufw $command proto tcp from any to any port 443
1:q
